url: http://www.cleanrobotics.com
#baseurl: /cleanrobotics

# Site settings
title: CleanRobotics
email: teamtrashbot@gmail.com
description: "CleanRobotics makes waste management smart with Trashbot™, a robotic trash can that automatically separates landfill waste from recyclables."
logo-header: img/logos/logo-text-small.png

# Identity settings

## Color settings (hex-codes without the leading hash-tag)
## http://paletton.com/palette.php?uid=5310u0koWxrf1LkknD3vguKvNne
color:
  primary: 28B573
  secondary: 2D77A7
  secondary-dark: 313335

## Font headings. Number indicates order of fallback
font:
  heading1: 'Hind Siliguri'
  heading2: Helvetica
  heading3: Arial
  heading4: sans-serif
  heading5: sans-serif
  body1: 'Hind Siliguri'
  body2: Helvetica
  body3: Arial
  body4: sans-serif
  body5: sans-serif

# Team names, titles and social links
people:
- first: Vaish 
  last: Krishnamurthy
  pic: staff_vaish
  position: CEO
  info: Vaish brings 10+ years of software and product development in a variety of industries ranging from telecommunications to health care. She holds a MS in Electrical Engineering from University of California, Riverside.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- first: Charles
  last: Yhap
  pic: staff_charles
  position: COO
  info: Charles is an experienced social entrepreneur and has worked in the fields of human rights and environmental protection. He has 10 years of experience and thrives in a mission driven start-up organization.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- first: Koushil
  last: Sreenath
  pic: staff_koushil
  position: CTO
  info: Koushil is the technical co-founder of the TrashBot and is a professor of Mechanical Engineering at CMU. Koushil built a bipedal robot that was featured in Discovery channel, CNN, ESPN, Fox and CBS.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- first: Zeynep
  last: Tolon
  pic: staff_zeynep
  position: Senior Marketing Strategist
  info: Zeynep is a senior marketing and business strategist with experience working for the largest companies in the world, including McKinsey, IBM and Microsoft.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CleanRobotics
  - title: facebook
    url: https://www.facebook.com/CleanRobotics-911640895594874
  - title: linkedin
    url: https://www.linkedin.com/company/cleanrobotics
  - title: instagram
    url: https://www.instagram.com/clean_robotics/
  - title: google-plus
    url: https://plus.google.com/109641100732275034876

# Postal address (add as many lines as necessary)
address:
  - line: AlphaLab Gear, East Liberty
  - line: Pitsburgh, Pennsylania

# Build settings
markdown: kramdown
permalink: pretty


# Job postings

careers:
- title: VP of Engineering
  date: 2016-05-27
  description: We are looking for someone to serve as architect and leader for the CleanRobotics engineering team, responsible for both current and new product development as well as associated pilots.  Someone who is passionate about the environment but also has the technical chops from training and experience. Knows how to get people to hit deadlines and can help them overcome technical challenges. Someone who is focused on creating quality products and doing it right the first time!
  scope:
    - New product system architecture including technology, protocol and component selection
    - Management and mentorship of hardware, embedded software, and test teams
    - Collaborate with CEO, COO and CTO to develop product roadmap
    - Implementing and executing product road map as it applies to hardware, sensors, and embedded software and machine learning.
    - Recruiting engineering talent required to execute product roadmap.
    - Support transfer process from design and piloting to manufacturing.
  skills:
    - Leading and managing complex engineering projects through full product development life cycle
    - Background in microcontroller circuit design (AVR, ARM)
    - Background in programming (JAVA,C, C++)
    - Background in RF communication protocols (Specifically Bluetooth Low Energy, WiFi)
    - Experience in power and memory management, algorithm design, signal processing, sensor selection and design, automation.
    - Experience in material classification and manufacturing a plus
    - Android OS experience preferred
  quals:
    - Master’s degree or greater in mechanical engineering, robotics, computer science or electrical engineering required.
    - 2+ years experience in a hands-on technical role required.
  other: Please note that this position is full-time at Pittsburgh headquarters. Must be local or willing to relocate. Must be a US Citizen, or a foreign citizen with required work visa. Some national or international travel maybe required for factory visits/supervision, possibly for extended periods of 2 months or more.
  contact: To inquire about this position, please contact Vaish Krishnamurthy at <a href="mailto:Vaish@cleanrobotics.com">Vaish@cleanrobotics.com</a>