url: http://www.cleanrobotics.com
#baseurl: /cleanrobotics

# Site settings
title: CleanRobotics
email: teamtrashbot@gmail.com
description: "CleanRobotics makes waste management smart with Trashbot™, a robotic trash can that automatically separates landfill waste from recyclables."
logo-header: img/logos/logo-text-small.png

# Build settings
markdown: kramdown
permalink: pretty

# Identity settings

## Color settings (hex-codes without the leading hash-tag)
## http://paletton.com/palette.php?uid=5310u0koWxrf1LkknD3vguKvNne
color:
  primary: 28B573
  secondary: 2D77A7
  secondary-dark: 313335

## Font headings. Number indicates order of fallback
font:
  heading1: 'Hind Siliguri'
  heading2: Helvetica
  heading3: Arial
  heading4: sans-serif
  heading5: sans-serif
  body1: 'Hind Siliguri'
  body2: Helvetica
  body3: Arial
  body4: sans-serif
  body5: sans-serif

# Team names, titles and social links
people:
- first: Charles
  last: Yhap
  pic: staff_charles
  position: CEO
  type: leadership
  info: Charles is an experienced social entrepreneur and has worked in the fields of human rights and environmental protection. He has 10 years of experience and thrives in a mission driven start-up organization.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- first: Tanner
  last: Cook
  pic: staff_tanner
  position: VP of Engineering
  type: leadership
  info: Tanner brings a wealth of engineering and research experience from multiple years working for and founding advanced technology startups such as Higea Technologies and Innoven Energy.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- first: Aakash
  last: Pathak
  pic: staff_aakash
  position: VP of Marketing & Business Development
  type: leadership
  info: Possessing a natural hustle and entrepreneurial spirit, Aakash brings strong experience in Product Strategy, Product Marketing, Go-to-Market, and Growth Hacking. With an MS in Entrepreneurship and Innovation Management from CMU, he seeks to use his suite of skills to help change the world.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- first: Zeynep
  last: Tolon
  pic: staff_zeynep
  position: Senior Marketing Strategist
  type: leadership
  info: Zeynep is a senior marketing and business strategist with experience working for the largest companies in the world, including McKinsey, IBM and Microsoft.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- first: Jayanth
  last: Sharma
  pic: staff_jayanth
  position: Director of Electronic Systems
  type: leadership
  info: Jayanth is a recent graduate of CMU with a Masters in Electrical Engineering. He brings a robust knowledge of a variety of electrical systems.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- first: Jennifer 
  last: Trinh
  pic: staff_jen
  position: Director of Operations
  type: leadership
  info: Jen is an experienced project leader in technical startup environments. She has a PhD in physics from UC Santa Cruz, where, as a National Science Foundation Graduate Research Fellow, she performed research and managed operations at a newly-created lab focused on quantum materials. She is passionate about sustainability and promoting scientific literacy and diversity in science and tech.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #      
- first: Vaish 
  last: Krishnamurthy
  pic: staff_vaish
  position: Board Chair
  type: advisory
  info: Vaish brings 10+ years of software and product development in a variety of industries ranging from telecommunications to health care. She holds a MS in Electrical Engineering from University of California, Riverside.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- first: Koushil
  last: Sreenath
  pic: staff_koushil
  position: Technical Advisor
  type: advisory
  info: Koushil is the technical co-founder of the TrashBot and is a professor of Mechanical Engineering at CMU. Koushil built a bipedal robot that was featured in Discovery channel, CNN, ESPN, Fox and CBS.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CleanRobotics
  - title: facebook
    url: https://www.facebook.com/CleanRobotics-911640895594874
  - title: linkedin
    url: https://www.linkedin.com/company/cleanrobotics
  - title: instagram
    url: https://www.instagram.com/clean_robotics/
  - title: google-plus
    url: https://plus.google.com/109641100732275034876
  - title: youtube
    url: https://www.youtube.com/channel/UCriG8-zco2SFzFAvsaJsfjw

# Postal address (add as many lines as necessary)
address:
  - line: AlphaLab Gear, East Liberty
  - line: Pitsburgh, Pennsylania

# Job postings
## description: each bullet is rendered as a paragraph at the beginning
## scope, skills, quals, money: each bullet is rendered as a bullet
## date and contact: rendered on the side in full screen, before description in mobile
## postscript: each bullet is rendered as a paragraph at the end
## other: rendered as an italics paragraph after everything else

careers:
- title: Electrical Engineer
  ##date: 2017-9-13
  description:
    - We are looking to bring on a top-notch Electrical Engineer who will work with us to create the next generation of CleanRobotics technology. At CleanRobotics, you will work with a team of passionate innovators to create hardware and firmware that will change the way we deal with waste. You'll work in an award winning office with smart designs, large common areas, and an open floor plan that fuels collaboration.
  quals: 
    - Bachelor’s or Master’s degree in Electrical Engineering
    - Proficient at PCB layout, electronic assembly, and troubleshooting circuits with an oscilloscope
    - Proficient at writing firmware (C/C++) for MCUs in embedded systems
    - Hands-on experience through previous jobs, student teams, co-op, and/or personal projects
  scope:
    - Develop hardware and firmware for TrashBot
    - Test, characterize and iterate existing designs
    - Evaluate new sensor technologies and assess for applicability to our projects
    - Create production testing solutions for electronic assemblies
  skills:
    Preferred Skills&#58
    - Experience with common communication protocols (SPI, UART, CAN) 
    - Experience with Computer Vision
    - Experience with SolidWorks/AutoCAD
    - Proficiency in C/C++ and Python
    - Familiarity with Machine Learning
    - Familiarity with version control systems such as Subversion and GitHub/GitLab
    -	Familiarity with sensor interfaces, such as LIDAR, GPS, and RADAR
    Other Skills&#58
    •	Fast learner&#58 We’re looking for team members who thrive on applying their knowledge, learning new technologies and don’t believe in one-size-fits-all solutions. You should be able to adapt easily to meet the rapid pace of a rapidly evolving research, development, and testing environment.
    •	Fearlessness&#58 You think a working proof-of-concept is the best way to make a point. You strive on proving that speed and quality are not conflicting; that you can achieve both at the same time.
    •	Versatility&#58 In addition to having an intimate knowledge of core engineering fields, you understand how all the pieces fit together into integrated systems, and how they impact performance.
    •	Passion&#58 You feel ownership over everything you ship; you'd never call code or design "released" until you’re confident it’s correct. You pride yourself on efficient monitoring, strong documentation, and proper test coverage.
    •	Team player&#58 You believe that you can achieve more on a team — that the whole is greater than the sum of its parts. You rely on others' candid feedback for continuous improvement.

  money: 
  other: Please note that this position is full-time at our Pittsburgh headquarters, with the possibility of moving to Colorado. Must be local or willing to relocate. Must be willing to travel. Must be a US Citizen, or a foreign citizen with required work visa. 
  contact: To inquire about this position, please contact Tanner Cook at <a href="mailto:tanner@cleanrobotics.com">tanner@cleanrobotics.com</a>.

  character:
    - Extraordinary drive and focus on long-term value  
    - Bright, quick, articulate, excellent presentation and interpersonal skills, and able to adapt to different internal and external constituencies
    - Viewed as a team player who also possesses the independence of thought and opinion to provide candor and honesty when making engineering decisions
    - Strategic thinker balanced with a grasp of the details
  postscript:
    - If you believe you have the unique blend of knowledge, skills, drive and abilities, we invite you to explain to us why you think you would fit in, how you could help build the firm, and what you could bring to the role.
    - Please submit your resume and&mdash;in-lieu of a cover letter&mdash;please write a statement about your reasoning for applying and how you believe you can contribute to CleanRobotics.
