url: http://www.cleanrobotics.com
#baseurl: /cleanrobotics

# Site settings
title: CleanRobotics
email: teamtrashbot@gmail.com
description: "CleanRobotics makes waste management smart with Trashbot™, a robotic trash can that automatically separates landfill waste from recyclables."
logo-header: img/logos/logo-text-small.png

# Identity settings

## Color settings (hex-codes without the leading hash-tag)
## http://paletton.com/palette.php?uid=5310u0koWxrf1LkknD3vguKvNne
color:
  primary: 28B573
  secondary: 2D77A7
  secondary-dark: 313335

## Font headings. Number indicates order of fallback
font:
  heading1: 'Hind Siliguri'
  heading2: Helvetica
  heading3: Arial
  heading4: sans-serif
  heading5: sans-serif
  body1: 'Hind Siliguri'
  body2: Helvetica
  body3: Arial
  body4: sans-serif
  body5: sans-serif

# Team names, titles and social links
people:
- first: Vaish 
  last: Krishnamurthy
  pic: staff_vaish
  position: CEO
  info: Vaish brings 10+ years of software and product development in a variety of industries ranging from telecommunications to health care. She holds a MS in Electrical Engineering from University of California, Riverside.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- first: Charles
  last: Yhap
  pic: staff_charles
  position: COO
  info: Charles is an experienced social entrepreneur and has worked in the fields of human rights and environmental protection. He has 10 years of experience and thrives in a mission driven start-up organization.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- first: Koushil
  last: Sreenath
  pic: staff_koushil
  position: CTO
  info: Koushil is the technical co-founder of the TrashBot and is a professor of Mechanical Engineering at CMU. Koushil built a bipedal robot that was featured in Discovery channel, CNN, ESPN, Fox and CBS.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- first: Zeynep
  last: Tolon
  pic: staff_zeynep
  position: Senior Marketing Strategist
  info: Zeynep is a senior marketing and business strategist with experience working for the largest companies in the world, including McKinsey, IBM and Microsoft.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CleanRobotics
  - title: facebook
    url: https://www.facebook.com/CleanRobotics-911640895594874
  - title: linkedin
    url: https://www.linkedin.com/company/cleanrobotics
  - title: instagram
    url: https://www.instagram.com/clean_robotics/
  - title: google-plus
    url: https://plus.google.com/109641100732275034876

# Postal address (add as many lines as necessary)
address:
  - line: AlphaLab Gear, East Liberty
  - line: Pitsburgh, Pennsylania

# Build settings
markdown: kramdown
permalink: pretty


# Job postings
## description: each bullet is rendered as a paragraph at the beginning
## scope, skills, quals, money: each bullet is rendered as a bullet
## date and contact: rendered on the side in full screen, before description in mobile
## postscript: each bullet is rendered as a paragraph at the end
## other: rendered as an italics paragraph after everything else

careers:
- title: Vice President of Engineering
  date: 2016-05-27
  description:
    - We are looking for someone to serve as architect and leader for the CleanRobotics engineering team, responsible for both current and new product development as well as associated pilots&#58; Someone who is passionate about the environment but also has the technical chops from training and experience. Knows how to get people to hit deadlines and can help them overcome technical challenges. Someone who is focused on creating quality products and doing it right the first time! The fast-paced entrepreneurial environment and unique founding leadership opportunities are not for everyone. We are looking for a confident leader who thinks way outside the box and who possess business savvy, entrepreneurial instincts and risk tolerance to excel in the CleanRobotics team.
  scope:
    - New product system architecture including technology, protocol and component selection
    - Management and mentorship of hardware, embedded software, and test teams
    - Collaborate with CEO, COO and CTO to develop product roadmap
    - Implementing and executing product road map as it applies to hardware, sensors, and embedded software and machine learning.
    - Recruiting engineering talent required to execute product roadmap.
    - Support transfer process from design and piloting to manufacturing.
  skills:
    - Leading and managing complex engineering projects through full product development life cycle
    - Background in microcontroller circuit design (AVR, ARM)
    - Background in programming (JAVA,C, C++)
    - Background in RF communication protocols (Specifically Bluetooth Low Energy, WiFi)
    - Experience in power and memory management, algorithm design, signal processing, sensor selection and design, automation.
    - Experience in material classification and manufacturing a plus
    - Android OS experience preferred
  quals:
    - Master’s degree or greater in mechanical engineering, robotics, computer science or electrical engineering required.
    - 2+ years experience in a hands-on technical role required.
  other: Please note that this position is full-time at Pittsburgh headquarters. Must be local or willing to relocate. Must be a US Citizen, or a foreign citizen with required work visa. Some national or international travel maybe required for factory visits/supervision, possibly for extended periods of 2 months or more.
  contact: To inquire about this position, please contact Vaish Krishnamurthy or Charles Yhap at <a href="mailto:founders@cleanrobotics.com">founders@cleanrobotics.com</a>.
  money:
    - Equity stake commensurate with first key hire.
    - Salary negotiable, but delayed. You're coming in on the ground floor of a start-up.
- title: Vice President of Marketing and Business Development
  date: 2016-11-05
  description:
    - We are looking for a person passionate about the environment and entrepreneurship&#58; someone with a strong foundation in business balanced by strong humanity; someone who knows how to get people to hit deadlines and can help them overcome challenges; a confident leader who thinks way outside the box and who possess business savvy, entrepreneurial instincts, and risk tolerance to excel in the CleanRobotics team.
  scope:
    - Prepare overall marketing strategy.
    - Develop programs with quantifiable objectives to measure results.
    - Implement and manage marketing budget.
    - Leverage data and analytics to drive insights.
    - Modify or redirect business intelligence strategy.
    - Build, oversee and direct the efforts of the marketing team.
    - Develop segmentation, competitive analysis/market intelligence, prospecting, lead generation, product and market development, pricing, promotions, communications and budgets, sales force effectiveness, strategic planning, services units and revenue retention and growth.
    - Develop and measure key metrics around the business including user acquisition, conversion rates, engagement rates, satisfaction and renewal rates.
    - Meet Company’s revenue goals, increase customer base, add to existing customer profitability and expand existing channels
    - Identify, design, develop and implement market-driven products and services to achieve the company’s mission 
    - Participate in strategic planning processes to ensure corporate strategies align with market drivers and support a customer intimate approach 
    - Identify and measure the key activities that create success in the marketplace then implement corporate policies, practices and metrics to ensure alignment 
    - Identify potential strategic partners, alliances and relationships to expand core product lines or bring new product lines to the organization 
    - Collaborate with leadership and professional staff to develop and deliver new products and services 
    - Foster, promote and facilitate a customer-oriented focus that advocates consultative client relationships and leverages cross-selling of company-wide products and capabilities 
    - Develop and maintain high-profile external relationships within client constituents, professional organizations, etc.(public relations presence) 
    - Review business development performance  
    - Create a knowledge transfer philosophy for both internal and external constituents, then implement policies and practices including training program for all aspects of the business development process that leverage video training modules via the corporate internet, intranet and extranet
  skills:
    - Proven leadership skills in business development, enterprise sales. 
    - Strong organization and prioritization skills
    - Strong communication and negotiation skills
    - Strong interpersonal and customer relations skills
    - Demonstrated track record of building business and developing capabilities in sales
    - Demonstrated ability to attract, influence and mentor other executives and leaders within an organization
    - Proven and verifiable track record of increasing revenues leading to profitability; having successfully managed revenue and profit centers a plu
    - Ability to establish a strong communication link and credibility with clients, potential clients, professional staff and management teams through the highest level of professionalism, integrity, mutual respect, and value added mentality
    - Strong entrepreneurial instincts with the passion, determination and experience to build a fast growth business
  quals:
    - Bachelors with 4-6 years’ experience, or MBA or equivalent education with 2-3 years’ experience
  other: Please note that this position is full-time at Pittsburgh headquarters. Must be local or willing to relocate. Must be a US Citizen, or a foreign citizen with required work visa. Some national or international travel maybe required for factory or site visits/supervision, possibly for extended periods of 2 months or more.
  contact: To inquire about this position, please contact Vaish Krishnamurthy or Charles Yhap at <a href="mailto:founders@cleanrobotics.com">founders@cleanrobotics.com</a>.
  money:
    - Equity stake commensurate with first key hire.
    - Salary negotiable, but delayed. You're coming in on the ground floor of a start-up.
  character:
    - Extraordinary drive and focus on long-term value  
    - Bright, quick, articulate, excellent presentation and interpersonal skills, and able to adapt to different internal and external constituencies
    - Viewed as a team player who also possesses the independence of thought and opinion to provide candor and honesty when making key business decisions 
    - Passionate about business results, with a strong sense of accountability, metrics and ownership
    - Strategic thinker balanced with a grasp of the details
  postscript:
    - A fundamental measure of success for the position will be increased and sustainable revenue that meets or exceeds goals.
    - If you believe you have the unique blend of knowledge, skills, drive and abilities, we invite you to explain to us why you think you would fit in, how you could help build the firm, and what you could bring to the role.
    - Please submit your resume and&mdash;in-lieu of a cover letter&mdash;please write a statement about your reasoning for applying and how you believe you can contribute. Please be as specific and succinct as possible and address your contribution in the areas of&#58;<ul><li>New Client Development</li><li>Innovative Business Practices</li><li>Marketing</li><li>Talent Management</li><li>Firm Culture</li></ul>
