url: http://www.cleanrobotics.com
#baseurl: /cleanrobotics

# Site settings
title: CleanRobotics
email: teamtrashbot@gmail.com
description: "CleanRobotics makes waste management smart with Trashbot™, a robotic trash can that automatically separates recyclables from landfill waste."
logo-header: img/logos/logo-text-small.png

# Build settings
markdown: kramdown
permalink: pretty

# Identity settings

## Color settings (hex-codes without the leading hash-tag)
## http://paletton.com/palette.php?uid=5310u0koWxrf1LkknD3vguKvNne
color:
  primary: 28B573
  secondary: 2D77A7
  secondary-dark: 313335

## Font headings. Number indicates order of fallback
font:
  heading1: 'Hind Siliguri'
  heading2: Helvetica
  heading3: Arial
  heading4: sans-serif
  heading5: sans-serif
  body1: 'Hind Siliguri'
  body2: Helvetica
  body3: Arial
  body4: sans-serif
  body5: sans-serif

# Team names, titles and social links
people:
- first: Charles
  last: Yhap
  pic: staff_charles
  position: CEO & Co-Founder
  type: leadership
  info: Charles is an experienced social entrepreneur and has worked in the fields of human rights and environmental protection. He has 10 years of experience and thrives in mission-driven start-up environments.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- first: Tanner
  last: Cook
  pic: staff_tanner
  position: VP of Engineering & Co-Founder
  type: leadership
  info: Tanner brings a wealth of engineering and research experience from multiple years working for and founding advanced technology startups such as Higea Technologies and Innoven Energy.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- first: Aakash
  last: Pathak
  pic: staff_aakash2
  position: VP of Product Commercialization
  type: leadership
  info: Aakash brings strong experience in Product Strategy, Product Marketing, Go-to-Market, and Growth. He has an MS in Entrepreneurship and Innovation Management from CMU.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- first: Grant
  last: Halleran
  pic: staff_grant
  position: Director of Hardware Engineering
  type: advisory
  info: Grant is a graduate student at CMU in Engineering and Technology Innovation Management, with an undergraduate degree in Mechanical Engineering. He brings technical expertise in design for manufacturing, product development, and hardware engineering.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
#- first: Jennifer 
 # last: Trinh
 # pic: staff_jen1
 # position: Director of Technical Operations
 # type: advisory
 # info: Jen is an experienced project leader in technical startup environments. She has a PhD in physics from UC Santa Cruz, where she was an NSF Graduate Research Fellow. She is passionate about sustainability and promoting scientific literacy and diversity in science and tech.
 # social:  
  #  - title: twitter
  #    url: #
   # - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #      
- first: Ian 
  last: Magazine
  pic: staff_ian
  position: Advisor
  type: advisory
  info: Ian Magazine has been a founder, investor and finance and operating executive for a host of enterprises in the wireless communications industry and a highly successful serial entrepreneur who has worked with breakthrough innovations in a range of technologies from wireless power transmission, to biotechnology and 360° Videography.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
#- first: Koushil
#  last: Sreenath
#  pic: staff_koushil
#  position: Technical Advisor
#  type: advisory
#  info: Koushil is the technical co-founder of the TrashBot and is a professor of Mechanical Engineering at CMU. Koushil built a bipedal robot that was featured in Discovery channel, CNN, ESPN, Fox and CBS.
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CleanRobotics
  - title: facebook
    url: https://www.facebook.com/CleanRobotics-911640895594874
  - title: linkedin
    url: https://www.linkedin.com/company/cleanrobotics
  - title: instagram
    url: https://www.instagram.com/clean_robotics/
  - title: google-plus
    url: https://plus.google.com/109641100732275034876
  - title: youtube
    url: https://www.youtube.com/channel/UCriG8-zco2SFzFAvsaJsfjw

# Postal address (add as many lines as necessary)
address:
  - line: AlphaLab Gear, East Liberty
  - line: Pittsburgh, Pennsylania

# Job postings
## description: each bullet is rendered as a paragraph at the beginning
## scope, skills, quals, money: each bullet is rendered as a bullet
## date and contact: rendered on the side in full screen, before description in mobile
## postscript: each bullet is rendered as a paragraph at the end
## other: rendered as an italics paragraph after everything else

careers:
- title: Full-stack Embedded Systems Engineer
  date: 2018-6-1
  description:
    - We are looking to bring on a top-notch Full-stack Embedded Systems Engineer who will work with us to create the next generation of CleanRobotics technology. You will be part of a team of passionate innovators who seek to change the way we deal with waste.
  quals: 
    - Bachelor’s or Master’s degree in Computer Science, Computer Engineering, or related
    - Experience with machine learning / artificial intelligence / computer vision for real-world applications
    - Advanced at writing firmware for MCUs in embedded systems
    - Minimum 2 years work experience in a robotics or embedded software programming role, working with a team of engineers to solve complex problems 
  scope:
    - Research, develop, and adapt new technologies in machine learning / computer vision for use in waste sorting applications
    - Work alongside other engineers to prototype and implement embedded software systems in the next generation of TrashBots
    - Evaluate new sensor technologies and assess for applicability to our projects
    - Debug software / hardware issues
  skills:
    - Advanced in C/C++ and Python
    - Familiarity with version control systems such as Subversion and Git
    - Experience with sensor interfaces for item detection / recognition (preferred)
  
  money: 
  other: This is a mid-level position based in Pittsburgh, PA. The Full-stack Embedded Systems Engineer will report directly to the VP of Engineering. Must be local or willing to relocate. Must be willing to travel. Must be a US Citizen, or a foreign citizen with required work visa. 
  contact: To inquire about this position, please contact Tanner Cook at <a href="mailto:tanner@cleanrobotics.com">tanner@cleanrobotics.com</a>.    NO RECRUITERS PLEASE!

  character:
    - Self-motivated -- you come to work each day with goals in mind and the focus to accomplish them
    - Self-directed -- you are able to deal with uncertainty and rapid shifts in direction and pace (startup life!)
    - Team player -- you are a good communicator who takes ownership of your work, but also thrive in collaborative environments
  postscript:
    - CleanRobotics is proud to be an equal-opportunity employer. Women and minorities are encouraged to apply!
    - If you believe you have the unique blend of knowledge, skills, drive, and abilities, we invite you to explain to us why you think you would fit in, how you could help build the firm, and what you could bring to the role.
    - Please submit your resume, a link to your portfolio, and&mdash;in lieu of a cover letter&mdash;please write a statement about your reasons for applying and how you believe you can contribute to CleanRobotics.
